name: evfinder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_naver_map: ^1.3.1
  flutter_sliding_box: ^1.1.5
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0
  permission_handler: ^11.0.1 #권한
  geolocator: ^12.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
